title: From Theory to Practical Skills
author: Ning Wang
email: wn19950602@163.com
description: > # this means to ignore newlines until "baseurl:"
  Dreaming to be a data scientist, I have learnt some theoretical basis of data analysis at school, yet I havn't got enough 
practical experience. Now I am planning to review what I have learnt before and to verify those knowledge by going through
some data analysis projects.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
